import { Toaster } from "react-hot-toast";
import "./globals.css";
import Providers from "./providers";

export const metadata = {
  title: "Task Flow",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="h-screen antialiased flex overflow-hidden"
        suppressHydrationWarning>
        <Toaster />
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
